# Generated by Django 3.1.3 on 2021-04-04 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=30, null=True, verbose_name='Título')),
            ],
            options={
                'verbose_name': 'Home',
                'verbose_name_plural': 'Home',
                'ordering': ['title'],
            },
        ),
    ]
