# Generated by Django 3.1.3 on 2020-11-21 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, null=True, verbose_name='Nº')),
                ('a', models.TextField(blank=True, null=True, verbose_name='A')),
                ('b', models.TextField(blank=True, null=True, verbose_name='B')),
                ('c', models.TextField(blank=True, null=True, verbose_name='C')),
                ('d', models.TextField(blank=True, null=True, verbose_name='D')),
                ('answer', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, null=True, verbose_name='Respuesta')),
            ],
            options={
                'verbose_name': 'Test',
                'verbose_name_plural': 'Test',
                'ordering': ['number'],
            },
        ),
    ]
