# Generated by Django 3.1.3 on 2021-04-04 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Modalidad')),
            ],
            options={
                'verbose_name': 'Modalidad',
                'verbose_name_plural': 'Modalidades',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, null=True, verbose_name='Nº')),
                ('question', models.TextField(blank=True, null=True, verbose_name='Pregunta')),
                ('a', models.TextField(blank=True, null=True, verbose_name='A')),
                ('b', models.TextField(blank=True, null=True, verbose_name='B')),
                ('c', models.TextField(blank=True, null=True, verbose_name='C')),
                ('d', models.TextField(blank=True, null=True, verbose_name='D')),
                ('answer', models.CharField(blank=True, choices=[('1', 'A'), ('2', 'B'), ('3', 'C'), ('4', 'D')], max_length=1, null=True, verbose_name='Respuesta')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('nameModality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.modality')),
            ],
            options={
                'verbose_name': 'Test',
                'verbose_name_plural': 'Test',
                'ordering': ['number'],
            },
        ),
    ]
