# Generated by Django 3.1.3 on 2021-04-22 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useranswers',
            options={'ordering': ['numberQuestion'], 'verbose_name': 'Respuesta de usuario', 'verbose_name_plural': 'Respuestas de usuarios'},
        ),
        migrations.CreateModel(
            name='TestCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.IntegerField(blank=True, null=True, verbose_name='Contador')),
                ('listQuestionsNumbers', models.TextField(blank=True, null=True, verbose_name='Array números preguntas')),
                ('modality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.modality')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contador de preguntas',
                'verbose_name_plural': 'Contadores de preguntas',
                'ordering': ['user', 'modality'],
            },
        ),
    ]
