# Generated by Django 3.1.3 on 2020-11-22 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_auto_20201122_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='answer',
            field=models.CharField(blank=True, choices=[('1', 'A'), ('2', 'B'), ('3', 'C'), ('4', 'D')], max_length=1, null=True, verbose_name='Respuesta'),
        ),
    ]
