# Generated by Django 3.1.3 on 2021-04-26 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_auto_20210422_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcounter',
            name='completed',
            field=models.BooleanField(blank=True, null=True, verbose_name='Completado'),
        ),
    ]
