# Generated by Django 3.1.3 on 2021-04-26 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_testcounter_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcounter',
            name='completed',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Completado'),
        ),
    ]
