# Generated by Django 3.1.3 on 2020-11-22 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_auto_20201122_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='question',
            field=models.TextField(blank=True, null=True, verbose_name='Pregunta'),
        ),
    ]
