# Generated by Django 3.1.3 on 2020-12-23 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_test_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='observations',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
    ]
